# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('face', models.URLField(blank=True, max_length=500, null=True, unique=True)),
                ('eventos', models.ManyToManyField(to='eventos.Eventos')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('pagina', models.URLField()),
                ('giro', models.CharField(max_length=100)),
                ('eventos', models.ManyToManyField(related_name='eventos', to='eventos.Eventos')),
            ],
            options={
                'ordering': ('giro',),
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('unidad', models.CharField(max_length=100)),
                ('costo_u', models.IntegerField()),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.AddField(
            model_name='proveedor',
            name='serv',
            field=models.ManyToManyField(related_name='Servicios', to='personas.Servicios'),
        ),
    ]
