# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import modules.eventos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('orden', models.CharField(max_length=500)),
                ('num_inv', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('lugar', models.CharField(max_length=300)),
                ('croquis', models.ImageField(upload_to=modules.eventos.models.user_directory_path)),
                ('tar', models.ManyToManyField(related_name='tareas', to='tareas.Tarea')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
    ]
