# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 22:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coment', models.TextField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SubTarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fcreacion', models.DateTimeField(default=datetime.datetime(2017, 8, 12, 22, 11, 10, 561628))),
                ('fplaneado', models.DateTimeField()),
                ('fcompletado', models.DateTimeField()),
                ('completado', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fcreacion', models.DateTimeField(default=datetime.datetime(2017, 8, 12, 22, 11, 10, 562654))),
                ('fplaneado', models.DateTimeField()),
                ('fcompletado', models.DateTimeField()),
                ('completado', models.BooleanField(default=False)),
                ('coment', models.ManyToManyField(related_name='comentarios', to='tareas.Comentario')),
                ('sub', models.ManyToManyField(related_name='subtareas', to='tareas.SubTarea')),
            ],
            options={
                'ordering': ('fplaneado',),
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.AddField(
            model_name='subtarea',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.Tipo'),
        ),
    ]
